### ISSUE TITLE
Add a DEBUG option in config

### ISSUE THREAD

**Issue by GlitchiKun** [BobbySoftwares/Bybbot#23]
When you run the bot in DEBUG mode, all the logs will be displayed localy instead in discord for avoid intense spamming of BobbySoftwares members.

**Comment by gggto** [comment]
Rather than a Debug option, just having the `#logs` chan id in the config.json instead of directly hardcoded in the source would do marvels

**Comment by GlitchiKun** [comment]
Why not both ?

or if log key is missing, then message are send localy

**Comment by gggto** [comment]
Since anyway we use completely different configurations for dev bots and production bots, I fail to see why we would specify a log chan id if it's to use local logging
If the `debug` flag purpose is just to ignore a `log-chan` config field then it's redundant with that field
